services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - app-network

  bot:
    build:
      context: .
      dockerfile: tg_bot/Dockerfile
    restart: unless-stopped
    environment:
      - MATSTAT_LUCKY_WHEEL_BOT_TOKEN=${MATSTAT_LUCKY_WHEEL_BOT_TOKEN}
    depends_on:
      - flask
    networks:
      - app-network

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - flask
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
